apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    {{- include "voting-app.selectorLabels" (dict "component" "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" (dict "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting-app.labels" . | nindent 8 }}
        {{- include "voting-app.selectorLabels" (dict "component" "worker") | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: {{ include "voting-app.image" (dict "registry" .Values.registry "image" .Values.worker.image) }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.worker.containerPort }}
              name: worker-port
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "voting-app.configMapName" . }}
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "voting-app.configMapName" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "voting-app.configMapName" . }}
                  key: POSTGRES_DB
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "voting-app.configMapName" . }}
                  key: REDIS_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting-app.secretName" . }}
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
