---
- name: SSH Hardening
  hosts: local
  become: true

  tasks:
    - name: Check if sshd_config exists
      stat:
        path: /etc/ssh/sshd_config
      register: ssh_config

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        backup: yes
      when: ssh_config.stat.exists

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        backup: yes
      when: ssh_config.stat.exists

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
      when: ssh_config.stat.exists
      ignore_errors: true
      