apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.result.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    {{- include "voting-app.selectorLabels" (dict "component" "result") | nindent 4 }}
spec:
  selector:
    {{- include "voting-app.selectorLabels" (dict "component" "result") | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.result.service.port }}
      targetPort: result-port
  type: {{ .Values.result.service.type }}
